### ISSUE TITLE
Control 2nd device

### ISSUE THREAD

**Issue by dgLAeS** [rowak/nanoleaf-desktop#3] opened 2019-05-01 22:22 UTC
1. connect to first device
1. use the _turn on|off_ button in _nanoleaf-desktop_ App - the first device switch the on/off state
1. connect to second device (device layout is displayed correctly in the _Preview_)
1. use the _turn on|off_ button in _nanoleaf-desktop_ App - the **first** device is still switched

(the application _Nanoleaf.for.Desktop.v0.7.0.WINDOWS_[binary] is used)
(no difference between _light panels_ or _canvas_)

**Comment by rowak** [comment] 2019-05-01 23:21
Give [this beta version](https://ufile.io/camiikug) a try for me and see if the problem is fixed. I don't actually own multiple Nanoleaf devices so I can't guarentee it works, but it *should* work.

**Comment by Galvarino** [comment] 2019-05-02 03:09
Hmm, I thought the app would switch control between the two auroras using the "Change Device" feature, in the top left. I don't believe two can be controlled at once by the same controls however. (I could be wrong)

**Comment by rowak** [comment] 2019-06-18 17:00
I'm pretty sure this is fixed as of v0.7.1 (6626a28) so I'm just going to go ahead and close this. Feel free to open it again if I'm wrong.

**Closed by rowak** 2019-06-18 17:00 UTC
Labels: bug
